version: '3.7'
services:
  api:
    container_name: boilerplate-api
    build: ./api
    ports:
      - '3333:3333'
    volumes:
      - ./api:/usr/app
    networks:
      - app-network
    command: yarn run dev

  mongodb:
    image: mongo:latest
    container_name: boilerplate-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
