version: '3.7'
services:
  admin:
    container_name: boilerplate-admin
    build: './admin'
    volumes:
      - ./admin:/app
      - ./admin/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - '3001:3000'

  api:
    container_name: boilerplate-api
    build: './api'
    volumes:
      - ./api:/usr/app
      - ./api/node_modules:/usr/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - '3333:3333'
  mongodb:
    image: mongo:latest
    container_name: boilerplate-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: rootpassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
